// ClientApp/React/src/App.tsx
import React from 'react';
import { Routes, Route, unstable_HistoryRouter as Router, Navigate } from 'react-router-dom';
import history from './utils/history'
import './App.css';
import HomePage from './Components/Pages/HomePage';

function App() {
  return (
    // <Router history={history}>
    //   <Routes>
    //     <Route path="/Home" element={HomePage}/>
    //   </Routes>
    // </Router>
    
    <div id="backDiv" className="appBody">

  <nav className="navbar navbar-expand-lg navbar-dark navColor">
    <img className="img-fluid" src="https://upload.wikimedia.org/wikipedia/commons/e/ef/Stack_Overflow_icon.svg" width="30"
      alt=""/>
    <a className="navbar-brand">Stackoverflow</a>
    <button className="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
      aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">Collapse</button>
    <div className="collapse navbar-collapse" id="collapsibleNavId">
      <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
        {/* <!-- Links on nav here --> */}
          <li className="btn btn-outline-light">+ Ask your question</li>
      </ul>
      <form className="form-inline my-2 my-lg-0">
        <input className="form-control mr-sm-2" type="text" placeholder="Search" name="searchText"/>
        <button className="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <div className="col-md-8 offset-2 navColor" >
    <HomePage/>
  </div>
</div>


  );
}

export default App;

// Angular/my-dream-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { LoginPartialComponent } from './login-partial/login-partial.component';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'my-dream-app';

  get getAuth(){
    return LoginPartialComponent.authenticated
  }

}

<div id="backDiv" class="body" >

<nav class=" navbar navbar-expand-lg navbar-dark" style="background-color: #555555;">
  <img class="img-fluid" src="https://upload.wikimedia.org/wikipedia/commons/e/ef/Stack_Overflow_icon.svg" width="30"
    alt="">
  <a class="navbar-brand" [routerLink]="['/']">Stackoverflow</a>
  <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
    aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
  <div class="collapse navbar-collapse" id="collapsibleNavId">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <!-- Links on nav here -->
      <ng-container *ngIf="getAuth">
        <li  class="btn btn-outline-light" [routerLink]="['AskQuestion']">+ Ask your question</li>        
      </ng-container>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <app-login-partial></app-login-partial>
  </div>
  </nav>

  <div class="row">
    <div class="col-md-2">
      <img src="https://angular.io/assets/images/logos/angular/angular.svg" alt="">
    </div>
    <div class="col-md-8">
      <router-outlet></router-outlet>
    </div>
    <div class="col-md-2">
      <img src="https://angular.io/assets/images/logos/angular/angular.svg" alt="">
    </div>
  </div>
</div>
