// ClientApp/React/src/Components/Pages/Question.tsx
import React from "react";

export default class Question extends React.Component {
  render() {
    return (
      <div>
        <div className="col-lg-10 offset-1">
          <h1 className="text-white display-1">Header</h1>
          <div>
            <p className="text-white">Discussion is opened</p>
            <p className="text-white">Discussion closed</p>
          </div>

          <div className="card text-white mb-5 bg-dark">
            <div className="card-header">
              <h2>Header</h2>
            </div>
            <div className="card-body"></div>
            <div className="card-footer">
              Created by: <a href="/" >author</a> on {"some dateTime"}
            </div>
          </div>
          <div>
            <h3>
              <p className="text-white">
                {" "}
                <b> answers</b>
              </p>
            </h3>

            <div className="mt-5">
              <div className="card text-white m-2 bg-dark">
                <div className="card-header">
                  <a href="/">author</a>
                </div>
                <div className="card-body"></div>
                <div className="card-footer">
                  <div className="row">
                    <div className="col-sm-8">Created on</div>
                    <div className="col-sm-2">
                      <p>Liked this</p>
                    </div>

                    <div className="col-sm-2">
                      <form method="post">
                        <input
                          type="button"
                          className="btn btn-secondary"
                          value="Like"
                        />
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div>
            <div>
              <h4 className="text-white">Add your own answer:</h4>
            </div>
            <div>
              <form>
                <input name="questionId" hidden type="text" />
                <textarea
                  required
                  name="body"
                  className="form-control mb-5 bg-dark text-white"
                  placeholder="Enter your answer"
                ></textarea>
                <input type="submit" value="Send" className="btn btn-primary" />
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

// Angular/my-dream-app/src/app/Question/Question.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-Question',
  templateUrl: './Question.component.html',
  styleUrls: ['./Question.component.scss']
})
export class QuestionComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="row">
  <div class="card card-body col-6 ml-0" >
    <h2>Question topic</h2>
    <div>
      <p>
        Discussion is opened
      </p>
    </div>

    <div class="card mb-5">
      <div class="card-header">
        <h2>
          Question Topic
        </h2>
      </div>
      <div class="card-body">
        Question body
      </div>
      <div class="card-footer">Created by: <a>Alex Peteson</a> on 24-05-2000 14:55</div>
    </div>
    <div>
      <h3>
        <p><b>10 answers</b></p>
      </h3>
      <div class="mt-5">
        <div class="card mb-2">
          <div class="card-header">
            <a href="/User" >Creator</a>
          </div>
          <div class="card-body">Some test body here</div>
          <div class="card-footer">
            <div class="row">
              <div class="col-sm-9">
                Created on 25-05-2000 14:55
              </div>
              <div class="col-sm-1">
                <form method="post" asp-page-handler="OnLike">
                  <input type="button" class="btn btn-secondary" value="Like" />
                </form>
              </div>
              <div class="col-sm-2">
                <p>
                  15 Liked this
                </p>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>


    <div>
      <h4>Add your own answer:</h4>
    </div>
    <div>
      <form method="post">
        <input type="text" hidden="true" name="Question.Id" />
        <textarea name="Body" class="form-control mb-5" placeholder="Enter your answer"></textarea>
        <input type="submit" value="Send" class="btn btn-primary" />
      </form>
    </div>

  </div>

</div>
